services:

  database:
    # Use the postgres 11.5 base image for this container.
    image: postgres:14.2

    volumes:
      - /var/lib/postgresql/data
    environment:
      RAILS_ENV: development
      DATABASE_NAME: Twitter_development
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: password
     
  web:
    # The root directory from which we're building.
    build: .

    # This makes it so any code changes inside the project
    # directory get synced with Docker. Without this line,
    # we'd have to restart the container every time we
    # changed a file.
    volumes:
      - .:/code:cached

    # The command to be run when we run "docker-compose up".
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    # Expose port 3000.
    ports:
      - "3000:3000"

    # Specify that this container depends on the other
    # container which we've called "database".
    depends_on:
      - database
    # Specify the values of the environment variables
    # used in this container.
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - web


# Declare the volumes that our application uses.
volumes:
  db_data: