services:

  database:
    # Use the postgres 11.5 base image for this container.
    image: postgres:14.2

    volumes:
      # We need to tell Docker where on the PostgreSQL
      # container we want to keep the PostgreSQL data.
      # In this case we're telling it to use a directory
      # called /var/lib/postgresql/data, although it
      # conceivably could have been something else.
      #
      # We're associating this directory with something
      # called a volume. (You can see all your Docker
      # volumes by running +docker volume ls+.) The name
      # of our volume is db_data.
      - /var/lib/postgresql/data
    environment:
      RAILS_ENV: development
      DATABASE_NAME: Twitter_development
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: password
     
  web:
    # The root directory from which we're building.
    build: .

    # This makes it so any code changes inside the project
    # directory get synced with Docker. Without this line,
    # we'd have to restart the container every time we
    # changed a file.
    volumes:
      - .:/code:cached

    # The command to be run when we run "docker-compose up".
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    # Expose port 3000.
    ports:
      - "3000:3000"

    # Specify that this container depends on the other
    # container which we've called "database".
    depends_on:
      - database
    # Specify the values of the environment variables
    # used in this container.
    env_file:
      - .env

# Declare the volumes that our application uses.
volumes:
  db_data: